import { ABeeZee } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const FiraCodeFont = ABeeZee({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={FiraCodeFont.className}>{children}</body>
    </html>
  );
}
